import mongoose from 'mongoose';

const Cart=new mongoose.Schema(
    {
        userId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'UserData',
            required:true,
        },
        productId:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Products',
            required:true,
        },
        productName:{
            type:String,
            required:true,
        },
        quantity:{
            type:Number,
            required:true,
        },
        price:{
            type:Number,
            required:true,
        },
        totalPrice:{
            type:Number,
            required:true,
        },
        imgSrc:{
            type:String,
            required:true,
        },
        stock_quantity:{
            type:Number,
            required:true,
        },
        product_is_veg:{
            type:Boolean,
            required:true,
        },
        product_type:{
            type:String,
            required:true,
        },
        max_quantity:{
            type:Number,
            required:true,
        },
        min_quantity:{
            type:Number,
            required:true,
        },
        pack_quantity:{
            type:Number,
            required:true,
        },
    },
    {
        timestamps:true,
    }
);

export default mongoose.model("CartData",Cart);